[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/gallery"
  to = "/.netlify/functions/gallery"
  status = 200

[[redirects]]
  from = "/api/gallery/*"
  to = "/.netlify/functions/gallery-id/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"] 